/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatosRouteImport } from './routes/datos'
import { Route as GobernanzaRouteImport } from './routes/gobernanza'
import { Route as InvestigacionesRouteImport } from './routes/investigaciones'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as InvestigacionesIndexRouteImport } from './routes/investigaciones.index'
import { Route as InvestigacionesSlugRouteImport } from './routes/investigaciones.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatosRoute = DatosRouteImport.update({
  id: '/datos',
  path: '/datos',
  getParentRoute: () => rootRouteImport,
} as any)
const GobernanzaRoute = GobernanzaRouteImport.update({
  id: '/gobernanza',
  path: '/gobernanza',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigacionesRoute = InvestigacionesRouteImport.update({
  id: '/investigaciones',
  path: '/investigaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigacionesIndexRoute = InvestigacionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvestigacionesRoute,
} as any)
const InvestigacionesSlugRoute = InvestigacionesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InvestigacionesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datos': typeof DatosRoute
  '/gobernanza': typeof GobernanzaRoute
  '/investigaciones': typeof InvestigacionesRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/investigaciones/$slug': typeof InvestigacionesSlugRoute
  '/investigaciones/': typeof InvestigacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datos': typeof DatosRoute
  '/gobernanza': typeof GobernanzaRoute
  '/nosotros': typeof NosotrosRoute
  '/investigaciones/$slug': typeof InvestigacionesSlugRoute
  '/investigaciones': typeof InvestigacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datos': typeof DatosRoute
  '/gobernanza': typeof GobernanzaRoute
  '/investigaciones': typeof InvestigacionesRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/investigaciones/$slug': typeof InvestigacionesSlugRoute
  '/investigaciones/': typeof InvestigacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datos'
    | '/gobernanza'
    | '/investigaciones'
    | '/nosotros'
    | '/investigaciones/$slug'
    | '/investigaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datos'
    | '/gobernanza'
    | '/nosotros'
    | '/investigaciones/$slug'
    | '/investigaciones'
  id:
    | '__root__'
    | '/'
    | '/datos'
    | '/gobernanza'
    | '/investigaciones'
    | '/nosotros'
    | '/investigaciones/$slug'
    | '/investigaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatosRoute: typeof DatosRoute
  GobernanzaRoute: typeof GobernanzaRoute
  InvestigacionesRoute: typeof InvestigacionesRouteWithChildren
  NosotrosRoute: typeof NosotrosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datos': {
      id: '/datos'
      path: '/datos'
      fullPath: '/datos'
      preLoaderRoute: typeof DatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gobernanza': {
      id: '/gobernanza'
      path: '/gobernanza'
      fullPath: '/gobernanza'
      preLoaderRoute: typeof GobernanzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigaciones': {
      id: '/investigaciones'
      path: '/investigaciones'
      fullPath: '/investigaciones'
      preLoaderRoute: typeof InvestigacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigaciones/': {
      id: '/investigaciones/'
      path: '/'
      fullPath: '/investigaciones/'
      preLoaderRoute: typeof InvestigacionesIndexRouteImport
      parentRoute: typeof InvestigacionesRoute
    }
    '/investigaciones/$slug': {
      id: '/investigaciones/$slug'
      path: '/$slug'
      fullPath: '/investigaciones/$slug'
      preLoaderRoute: typeof InvestigacionesSlugRouteImport
      parentRoute: typeof InvestigacionesRoute
    }
  }
}

interface InvestigacionesRouteChildren {
  InvestigacionesSlugRoute: typeof InvestigacionesSlugRoute
  InvestigacionesIndexRoute: typeof InvestigacionesIndexRoute
}

const InvestigacionesRouteChildren: InvestigacionesRouteChildren = {
  InvestigacionesSlugRoute: InvestigacionesSlugRoute,
  InvestigacionesIndexRoute: InvestigacionesIndexRoute,
}

const InvestigacionesRouteWithChildren = InvestigacionesRoute._addFileChildren(
  InvestigacionesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatosRoute: DatosRoute,
  GobernanzaRoute: GobernanzaRoute,
  InvestigacionesRoute: InvestigacionesRouteWithChildren,
  NosotrosRoute: NosotrosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
