/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgoraRouteImport } from './routes/agora'
import { Route as BalanceRouteImport } from './routes/balance'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as ErarioRouteImport } from './routes/erario'
import { Route as FronteraRouteImport } from './routes/frontera'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PiezasRouteImport } from './routes/piezas'
import { Route as PolisRouteImport } from './routes/polis'
import { Route as VidaComunRouteImport } from './routes/vida-comun'
import { Route as PiezasIndexRouteImport } from './routes/piezas.index'
import { Route as PiezasSlugRouteImport } from './routes/piezas.$slug'
import { Route as ApiWiwoV1ArticlesRouteImport } from './routes/api/wiwo/v1/articles'
import { Route as ApiWiwoV1ManifestRouteImport } from './routes/api/wiwo/v1/manifest'
import { Route as ApiWiwoV1MediaRouteImport } from './routes/api/wiwo/v1/media'
import { Route as ApiWiwoV1MediaIdRouteImport } from './routes/api/wiwo/v1/media.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgoraRoute = AgoraRouteImport.update({
  id: '/agora',
  path: '/agora',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceRoute = BalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const ErarioRoute = ErarioRouteImport.update({
  id: '/erario',
  path: '/erario',
  getParentRoute: () => rootRouteImport,
} as any)
const FronteraRoute = FronteraRouteImport.update({
  id: '/frontera',
  path: '/frontera',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PiezasRoute = PiezasRouteImport.update({
  id: '/piezas',
  path: '/piezas',
  getParentRoute: () => rootRouteImport,
} as any)
const PolisRoute = PolisRouteImport.update({
  id: '/polis',
  path: '/polis',
  getParentRoute: () => rootRouteImport,
} as any)
const VidaComunRoute = VidaComunRouteImport.update({
  id: '/vida-comun',
  path: '/vida-comun',
  getParentRoute: () => rootRouteImport,
} as any)
const PiezasIndexRoute = PiezasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PiezasRoute,
} as any)
const PiezasSlugRoute = PiezasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PiezasRoute,
} as any)
const ApiWiwoV1ArticlesRoute = ApiWiwoV1ArticlesRouteImport.update({
  id: '/api/wiwo/v1/articles',
  path: '/api/wiwo/v1/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWiwoV1ManifestRoute = ApiWiwoV1ManifestRouteImport.update({
  id: '/api/wiwo/v1/manifest',
  path: '/api/wiwo/v1/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWiwoV1MediaRoute = ApiWiwoV1MediaRouteImport.update({
  id: '/api/wiwo/v1/media',
  path: '/api/wiwo/v1/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWiwoV1MediaIdRoute = ApiWiwoV1MediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWiwoV1MediaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agora': typeof AgoraRoute
  '/balance': typeof BalanceRoute
  '/biblioteca': typeof BibliotecaRoute
  '/erario': typeof ErarioRoute
  '/frontera': typeof FronteraRoute
  '/nosotros': typeof NosotrosRoute
  '/piezas': typeof PiezasRouteWithChildren
  '/polis': typeof PolisRoute
  '/vida-comun': typeof VidaComunRoute
  '/piezas/$slug': typeof PiezasSlugRoute
  '/piezas/': typeof PiezasIndexRoute
  '/api/wiwo/v1/articles': typeof ApiWiwoV1ArticlesRoute
  '/api/wiwo/v1/manifest': typeof ApiWiwoV1ManifestRoute
  '/api/wiwo/v1/media': typeof ApiWiwoV1MediaRouteWithChildren
  '/api/wiwo/v1/media/$id': typeof ApiWiwoV1MediaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agora': typeof AgoraRoute
  '/balance': typeof BalanceRoute
  '/biblioteca': typeof BibliotecaRoute
  '/erario': typeof ErarioRoute
  '/frontera': typeof FronteraRoute
  '/nosotros': typeof NosotrosRoute
  '/polis': typeof PolisRoute
  '/vida-comun': typeof VidaComunRoute
  '/piezas/$slug': typeof PiezasSlugRoute
  '/piezas': typeof PiezasIndexRoute
  '/api/wiwo/v1/articles': typeof ApiWiwoV1ArticlesRoute
  '/api/wiwo/v1/manifest': typeof ApiWiwoV1ManifestRoute
  '/api/wiwo/v1/media': typeof ApiWiwoV1MediaRouteWithChildren
  '/api/wiwo/v1/media/$id': typeof ApiWiwoV1MediaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agora': typeof AgoraRoute
  '/balance': typeof BalanceRoute
  '/biblioteca': typeof BibliotecaRoute
  '/erario': typeof ErarioRoute
  '/frontera': typeof FronteraRoute
  '/nosotros': typeof NosotrosRoute
  '/piezas': typeof PiezasRouteWithChildren
  '/polis': typeof PolisRoute
  '/vida-comun': typeof VidaComunRoute
  '/piezas/$slug': typeof PiezasSlugRoute
  '/piezas/': typeof PiezasIndexRoute
  '/api/wiwo/v1/articles': typeof ApiWiwoV1ArticlesRoute
  '/api/wiwo/v1/manifest': typeof ApiWiwoV1ManifestRoute
  '/api/wiwo/v1/media': typeof ApiWiwoV1MediaRouteWithChildren
  '/api/wiwo/v1/media/$id': typeof ApiWiwoV1MediaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agora'
    | '/balance'
    | '/biblioteca'
    | '/erario'
    | '/frontera'
    | '/nosotros'
    | '/piezas'
    | '/polis'
    | '/vida-comun'
    | '/piezas/$slug'
    | '/piezas/'
    | '/api/wiwo/v1/articles'
    | '/api/wiwo/v1/manifest'
    | '/api/wiwo/v1/media'
    | '/api/wiwo/v1/media/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agora'
    | '/balance'
    | '/biblioteca'
    | '/erario'
    | '/frontera'
    | '/nosotros'
    | '/polis'
    | '/vida-comun'
    | '/piezas/$slug'
    | '/piezas'
    | '/api/wiwo/v1/articles'
    | '/api/wiwo/v1/manifest'
    | '/api/wiwo/v1/media'
    | '/api/wiwo/v1/media/$id'
  id:
    | '__root__'
    | '/'
    | '/agora'
    | '/balance'
    | '/biblioteca'
    | '/erario'
    | '/frontera'
    | '/nosotros'
    | '/piezas'
    | '/polis'
    | '/vida-comun'
    | '/piezas/$slug'
    | '/piezas/'
    | '/api/wiwo/v1/articles'
    | '/api/wiwo/v1/manifest'
    | '/api/wiwo/v1/media'
    | '/api/wiwo/v1/media/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgoraRoute: typeof AgoraRoute
  BalanceRoute: typeof BalanceRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ErarioRoute: typeof ErarioRoute
  FronteraRoute: typeof FronteraRoute
  NosotrosRoute: typeof NosotrosRoute
  PiezasRoute: typeof PiezasRouteWithChildren
  PolisRoute: typeof PolisRoute
  VidaComunRoute: typeof VidaComunRoute
  ApiWiwoV1ArticlesRoute: typeof ApiWiwoV1ArticlesRoute
  ApiWiwoV1ManifestRoute: typeof ApiWiwoV1ManifestRoute
  ApiWiwoV1MediaRoute: typeof ApiWiwoV1MediaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agora': {
      id: '/agora'
      path: '/agora'
      fullPath: '/agora'
      preLoaderRoute: typeof AgoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erario': {
      id: '/erario'
      path: '/erario'
      fullPath: '/erario'
      preLoaderRoute: typeof ErarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontera': {
      id: '/frontera'
      path: '/frontera'
      fullPath: '/frontera'
      preLoaderRoute: typeof FronteraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piezas': {
      id: '/piezas'
      path: '/piezas'
      fullPath: '/piezas'
      preLoaderRoute: typeof PiezasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polis': {
      id: '/polis'
      path: '/polis'
      fullPath: '/polis'
      preLoaderRoute: typeof PolisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vida-comun': {
      id: '/vida-comun'
      path: '/vida-comun'
      fullPath: '/vida-comun'
      preLoaderRoute: typeof VidaComunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piezas/': {
      id: '/piezas/'
      path: '/'
      fullPath: '/piezas/'
      preLoaderRoute: typeof PiezasIndexRouteImport
      parentRoute: typeof PiezasRoute
    }
    '/piezas/$slug': {
      id: '/piezas/$slug'
      path: '/$slug'
      fullPath: '/piezas/$slug'
      preLoaderRoute: typeof PiezasSlugRouteImport
      parentRoute: typeof PiezasRoute
    }
    '/api/wiwo/v1/articles': {
      id: '/api/wiwo/v1/articles'
      path: '/api/wiwo/v1/articles'
      fullPath: '/api/wiwo/v1/articles'
      preLoaderRoute: typeof ApiWiwoV1ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wiwo/v1/manifest': {
      id: '/api/wiwo/v1/manifest'
      path: '/api/wiwo/v1/manifest'
      fullPath: '/api/wiwo/v1/manifest'
      preLoaderRoute: typeof ApiWiwoV1ManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wiwo/v1/media': {
      id: '/api/wiwo/v1/media'
      path: '/api/wiwo/v1/media'
      fullPath: '/api/wiwo/v1/media'
      preLoaderRoute: typeof ApiWiwoV1MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wiwo/v1/media/$id': {
      id: '/api/wiwo/v1/media/$id'
      path: '/$id'
      fullPath: '/api/wiwo/v1/media/$id'
      preLoaderRoute: typeof ApiWiwoV1MediaIdRouteImport
      parentRoute: typeof ApiWiwoV1MediaRoute
    }
  }
}

interface PiezasRouteChildren {
  PiezasSlugRoute: typeof PiezasSlugRoute
  PiezasIndexRoute: typeof PiezasIndexRoute
}

const PiezasRouteChildren: PiezasRouteChildren = {
  PiezasSlugRoute: PiezasSlugRoute,
  PiezasIndexRoute: PiezasIndexRoute,
}

const PiezasRouteWithChildren =
  PiezasRoute._addFileChildren(PiezasRouteChildren)

interface ApiWiwoV1MediaRouteChildren {
  ApiWiwoV1MediaIdRoute: typeof ApiWiwoV1MediaIdRoute
}

const ApiWiwoV1MediaRouteChildren: ApiWiwoV1MediaRouteChildren = {
  ApiWiwoV1MediaIdRoute: ApiWiwoV1MediaIdRoute,
}

const ApiWiwoV1MediaRouteWithChildren = ApiWiwoV1MediaRoute._addFileChildren(
  ApiWiwoV1MediaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgoraRoute: AgoraRoute,
  BalanceRoute: BalanceRoute,
  BibliotecaRoute: BibliotecaRoute,
  ErarioRoute: ErarioRoute,
  FronteraRoute: FronteraRoute,
  NosotrosRoute: NosotrosRoute,
  PiezasRoute: PiezasRouteWithChildren,
  PolisRoute: PolisRoute,
  VidaComunRoute: VidaComunRoute,
  ApiWiwoV1ArticlesRoute: ApiWiwoV1ArticlesRoute,
  ApiWiwoV1ManifestRoute: ApiWiwoV1ManifestRoute,
  ApiWiwoV1MediaRoute: ApiWiwoV1MediaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
